apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
 name: omsagent-private-preview-windows
 namespace: kube-system
spec:
 updateStrategy:
  type: RollingUpdate
 template:
  metadata:
   labels:
    dsName: "omsagent-private-preview-windows-ds"
  spec:
   serviceAccountName: omsagent
   containers:
     - name: omsagent-private-preview-windows 
       image:  mcr.microsoft.com/azuremonitor/containerinsights/cidev:windowsprivatepreview_04232020_v1
       imagePullPolicy: Always
       resources:
        limits:
         cpu: 150m
         memory: 600Mi
        requests:
         cpu: 75m
         memory: 225Mi
       env:       
       - name: AKS_RESOURCE_ID
         value: "**"
       - name: AKS_REGION
         value: "**"
       - name: CONTROLLER_TYPE
         value: "DaemonSet"
       - name: CI_CERT_LOCATION
         value: "C://oms.crt"
       - name: CI_KEY_LOCATION
         value: "C://oms.key"
       - name: HOSTNAME
         valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
       volumeMounts:
        - mountPath: C:\ProgramData\docker\containers
          name: docker-windows-docker-containers
          readOnly: true
        - mountPath: C:\var
          name: docker-windows-kuberenetes-container-logs
        - mountPath: C:\etc\config\settings
          name: settings-vol-config
          readOnly: true
        - mountPath: C:\etc\omsagent-secret
          name: omsagent-secret
          readOnly: true
       livenessProbe:
        exec:
          command:
            - cmd
            - /c
            - C:\opt\omsagentwindows\scripts\cmd\livenessProbe.cmd
        failureThreshold: 3
        periodSeconds: 60
        initialDelaySeconds: 180
        successThreshold: 1
        timeoutSeconds: 10
   nodeSelector:
    beta.kubernetes.io/os: windows    
   # Tolerate a NoSchedule taint on master that ACS Engine sets.
   tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
   volumes:
    - name: docker-windows-kuberenetes-container-logs
      hostPath:
        path: C:\var
    - name: docker-windows-docker-containers
      hostPath:
        path: C:\ProgramData\docker\containers
    - name: settings-vol-config
      configMap:
        name: container-azm-ms-agentconfig
        optional: true  
    - name: omsagent-secret
      secret:
       secretName: omsagent-secret          
---
apiVersion: v1
kind: Secret
metadata:
  name: omsagent-secret
  namespace: kube-system
type: Opaque
data:
  #BASE64 ENCODED (Both WSID & WSKEY) INSIDE DOUBLE QUOTE ("")
  WSKEY: "**"
  WSID: "**"